version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - MODE=server
      - SQL_HOST=localhost
      - PORT=8000
      - BASE_URL=http://localhost:8000
    restart: unless-stopped

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"

volumes:
  postgres_data:
